# Generated by Django 5.2.8 on 2025-11-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_rename_sender_id_message_sender_message_conversation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="participants_id",
            new_name="participants",
        ),
    ]
