#!/bin/bash

set -e

echo " Starting Kubernetes cluster using Minikube..."
minikube start

echo " Verifying cluster status..."
kubectl cluster-info

echo " Retrieving available pods in all namespaces..."
kubectl get pods --all-namespaces

echo " Kubernetes cluster is up and running!"